import { applyAttributeMap, applyTextMap, localizePublicSeo, rewriteExactHrefs } from './i18n-page-utils.js';

export const LEGAL_PATHS = {
  privacy: { it: '/privacy-policy', de: '/de/datenschutz', en: '/en/privacy-policy' },
  cookies: { it: '/cookie-policy', de: '/de/cookie-richtlinie', en: '/en/cookie-policy' },
  terms: { it: '/termini-condizioni', de: '/de/agb', en: '/en/terms-and-conditions' },
  notice: { it: '/note-legali', de: '/de/impressum', en: '/en/legal-notice' },
  ai: { it: '/trasparenza-ai', de: '/de/ki-transparenz', en: '/en/ai-transparency' }
};

const META = {
  privacy: {
    de: { title: 'Datenschutz — Splendoria', description: 'Datenschutzhinweise von Splendoria zu Konten, redaktionellen Inhalten, KI-Funktionen, lokaler Sicherung, Aufbewahrung, Sicherheit und Betroffenenrechten.' },
    en: { title: 'Privacy Policy — Splendoria', description: 'Splendoria privacy information covering accounts, editorial content, AI features, local backups, retention, security and data-subject rights.' }
  },
  cookies: {
    de: { title: 'Cookie-Richtlinie — Splendoria', description: 'Technische Cookies und lokale Speichertechnologien bei Splendoria: keine Werbung, kein Profiling und kein websiteübergreifendes Tracking.' },
    en: { title: 'Cookie Policy — Splendoria', description: 'Technical cookies and local-storage technologies used by Splendoria: no advertising, no profiling and no cross-site tracking.' }
  },
  terms: {
    de: { title: 'Allgemeine Geschäftsbedingungen — Splendoria', description: 'Nutzungs- und Verkaufsbedingungen für das Splendoria Studio und die redaktionellen Leistungen.' },
    en: { title: 'Terms and Conditions — Splendoria', description: 'Terms of use and sale applying to the Splendoria Studio and editorial services.' }
  },
  notice: {
    de: { title: 'Impressum und rechtliche Hinweise — Splendoria', description: 'Anbieterkennzeichnung, Rechte an Inhalten, Verfügbarkeit, KI-Hinweise und externe Links der Website Splendoria.' },
    en: { title: 'Legal Notice — Splendoria', description: 'Provider identity, content rights, availability, AI notices and third-party links for the Splendoria website.' }
  },
  ai: {
    de: { title: 'Transparenz zur künstlichen Intelligenz — Splendoria', description: 'Klare Informationen über die Rolle der Muse, künstlicher Intelligenz, Nutzerkontrolle und menschlicher Aufsicht bei Splendoria.' },
    en: { title: 'Artificial Intelligence Transparency — Splendoria', description: 'Clear information about the role of the Muse, artificial intelligence, user control and human oversight at Splendoria.' }
  }
};

const CHROME = {
  de: [
    ['Come funziona', 'So funktioniert es'], ['Listino', 'Preise'], ['Guida', 'Leitfaden'], ['Contattaci', 'Kontakt'], ['Il mio Studio', 'Mein Studio'],
    ['La tua vita in un romanzo', 'Ihr Leben als Roman'], ['Guida allo Studio', 'Leitfaden zum Studio'], ['Termini e condizioni', 'Allgemeine Geschäftsbedingungen'], ['Note legali', 'Impressum'], ['Trasparenza IA', 'KI-Transparenz'],
    ['Privacy, senza sorprese', 'Datenschutz, ohne Überraschungen'],
    ['Usiamo solo strumenti tecnici necessari. Niente pubblicità, niente profilazione. Le bozze possono restare sul tuo dispositivo fino a 12 mesi come copia di sicurezza.', 'Wir verwenden nur technisch notwendige Werkzeuge. Keine Werbung, kein Profiling. Entwürfe können als Sicherungskopie bis zu 12 Monate auf Ihrem Gerät verbleiben.'],
    ['Privacy', 'Datenschutz'], ['Cookie e dati locali', 'Cookies und lokale Daten'], ['Ho capito', 'Verstanden'], ['Esci', 'Abmelden']
  ],
  en: [
    ['Come funziona', 'How it works'], ['Listino', 'Pricing'], ['Guida', 'Guide'], ['Contattaci', 'Contact us'], ['Il mio Studio', 'My Studio'],
    ['La tua vita in un romanzo', 'Your life as a novel'], ['Guida allo Studio', 'Studio Guide'], ['Termini e condizioni', 'Terms and Conditions'], ['Note legali', 'Legal Notice'], ['Trasparenza IA', 'AI Transparency'],
    ['Privacy, senza sorprese', 'Privacy, without surprises'],
    ['Usiamo solo strumenti tecnici necessari. Niente pubblicità, niente profilazione. Le bozze possono restare sul tuo dispositivo fino a 12 mesi come copia di sicurezza.', 'We use only the technical tools needed to provide the service. No advertising, no profiling. Drafts may remain on your device for up to 12 months as a safety copy.'],
    ['Cookie e dati locali', 'Cookies and local data'], ['Ho capito', 'Got it'], ['Esci', 'Log out']
  ]
};

const ATTRS = {
  de: [['Navigazione principale', 'Hauptnavigation'], ['Informazioni e assistenza', 'Informationen und Hilfe'], ['Chiudi l’informativa privacy', 'Datenschutzhinweis schließen'], ['Informazioni privacy', 'Datenschutzinformationen']],
  en: [['Navigazione principale', 'Main navigation'], ['Informazioni e assistenza', 'Information and support'], ['Chiudi l’informativa privacy', 'Close privacy notice'], ['Informazioni privacy', 'Privacy information']]
};

const BODIES = {
  privacy: {
    de: `<article class="legal-page"><header class="legal-hero"><div class="legal-reading"><p class="eyebrow">Schutz personenbezogener Daten</p><h1>Datenschutz</h1><p>Informationen gemäß Artikel 12 und 13 der Verordnung (EU) 2016/679. Wir erläutern klar, welche Daten wir verarbeiten, warum wir sie verarbeiten und wie lange wir sie aufbewahren.</p><p class="legal-updated">Letzte Aktualisierung: 29. August 2026</p></div></header><div class="legal-reading legal-content">
<section><h2>1. Verantwortlicher</h2><p>Verantwortlicher ist <strong>AI Arena di Raoul Ragazzi</strong>, Partita IVA 02950290219, Via Goethe 42, Meran und Via Settala 1, Mailand. Für Datenschutzanfragen, die Ausübung Ihrer Rechte oder Meldungen: <a href="mailto:contatti@splendoria.vip">contatti@splendoria.vip</a>.</p></section>
<section><h2>2. Welche Daten wir verarbeiten</h2><ul><li>Konto-, Kontakt-, Authentifizierungs- und Sicherheitsdaten;</li><li>geschäftliche Anfragen, Bestellungen und Verwaltungsdaten;</li><li>Erinnerungen, Interviews, Kapitel, Materialien und redaktionelle Präferenzen, die der Nutzer eingibt;</li><li>technische Daten, die zum Schutz des Dienstes erforderlich sind;</li><li>lokale Sicherungskopien von Entwürfen, die im Browser auf dem Gerät des Nutzers gespeichert werden, um versehentlichen Datenverlust zu vermeiden.</li></ul><p>Splendoria verkauft keine personenbezogenen Daten und verwendet sie weder für verhaltensbasierte Werbung noch für kommerzielles Profiling.</p></section>
<section><h2>3. Zwecke und Rechtsgrundlagen</h2><div class="legal-table-wrap"><table><thead><tr><th>Zweck</th><th>Rechtsgrundlage</th></tr></thead><tbody><tr><td>Konto, Studio, Schreiben, Unterstützung und Bereitstellung des Dienstes</td><td>Vertrag oder vorvertragliche Maßnahmen, Art. 6 Abs. 1 lit. b DSGVO</td></tr><tr><td>Kontakte, Angebote und Anfragen</td><td>Vorvertragliche Maßnahmen und berechtigtes Interesse an der Beantwortung, Art. 6 Abs. 1 lit. b und f DSGVO</td></tr><tr><td>Rechnungsstellung und Verwaltungspflichten</td><td>Vertrag und gesetzliche Verpflichtungen, Art. 6 Abs. 1 lit. b und c DSGVO</td></tr><tr><td>Sicherheit, Missbrauchsprävention und Schutz von Rechten</td><td>Berechtigtes Interesse, Art. 6 Abs. 1 lit. f DSGVO</td></tr><tr><td>Vom Nutzer angeforderte Muse- und KI-Funktionen</td><td>Erfüllung des angeforderten Dienstes, Art. 6 Abs. 1 lit. b DSGVO; ausdrückliche Einwilligung, wenn besondere Kategorien personenbezogener Daten des Nutzers erforderlich sind, Art. 9 Abs. 2 lit. a DSGVO</td></tr></tbody></table></div></section>
<section><h2>4. Sensible Erinnerungen und Daten anderer Personen</h2><p>Eine persönliche Geschichte kann besondere Kategorien personenbezogener Daten enthalten, etwa Angaben zur Gesundheit, zu religiösen oder politischen Überzeugungen, ethnischer Herkunft, Sexualleben oder sexueller Orientierung. Der Nutzer entscheidet, was er erzählt, und soll sich auf für das Projekt relevante Angaben beschränken. Wer Informationen, Fotografien oder Dokumente über Dritte einstellt, muss diese rechtmäßig verwenden dürfen und deren Würde, Privatsphäre und Rechte respektieren.</p></section>
<section><h2>5. Künstliche Intelligenz und menschliche Kontrolle</h2><p>Die als „Muse“ bezeichneten Funktionen nutzen Systeme künstlicher Intelligenz, um Fragen zu formulieren, Material zu ordnen, Entwürfe zu erstellen und Überarbeitungen vorzuschlagen. Der Nutzer wird über die Interaktion mit KI informiert, kann jede Ausgabe ändern oder ablehnen und behält die Kontrolle über das Werk. Es werden keine ausschließlich automatisierten Entscheidungen getroffen, die rechtliche oder ähnlich erhebliche Auswirkungen auf eine Person haben. Weitere Informationen finden Sie auf der Seite <a href="/trasparenza-ai">KI-Transparenz</a>.</p></section>
<section><h2>6. Sicherungskopie im Browser</h2><p>Im Studio können Texte und redaktionelle Felder zusätzlich im <strong>lokalen Speicher des Geräts bis zu 365 Tage nach der letzten Änderung</strong> gespeichert werden. Diese technische Kopie bleibt im Browser und wird nicht automatisch an Splendoria übertragen. Passwörter, Token, Sitzungen, E-Mail-Adressen und Dateien werden nicht einbezogen. Der Browser oder der Nutzer kann diese Kopie jederzeit löschen.</p></section>
<section><h2>7. Empfänger und Übermittlungen</h2><p>Daten können im erforderlichen Umfang von Anbietern für Cloud-Infrastruktur, Datenbanken, Sicherheit, E-Mail und KI, von autorisierten Fachleuten für redaktionelle Überarbeitung und Bearbeitung, von Beratern sowie von Behörden verarbeitet werden, wenn dies gesetzlich vorgesehen ist. Führt eine Verarbeitung zu einer Übermittlung außerhalb des Europäischen Wirtschaftsraums, werden die Instrumente nach Kapitel V DSGVO eingesetzt, etwa Angemessenheitsbeschlüsse oder Standardvertragsklauseln.</p></section>
<section><h2>8. Aufbewahrung</h2><p>Konten und Projekte werden für die Dauer der Geschäftsbeziehung und, soweit erforderlich, für anschließende gesetzliche Fristen oder zur Rechtsverteidigung aufbewahrt. Sitzungen dauern höchstens 30 Tage, Links zur Passwortwiederherstellung 30 Minuten, technische Sicherheits- und Auditereignisse bis zu 365 Tage. Lokale Entwurfskopien haben eine maximale Anwendungsdauer von 365 Tagen ab der letzten Änderung, sofern sie nicht zuvor im Browser gelöscht werden.</p></section>
<section><h2>9. Sicherheit</h2><p>Splendoria setzt angemessene technische und organisatorische Maßnahmen ein: verschlüsselte Verbindungen, kryptografisch abgeleitete Passwörter, HttpOnly- und Secure-Sitzungscookies, getrennte Zugriffe, Begrenzung von Versuchen und Protokollierung kritischer Ereignisse. Redaktionelle Inhalte werden nach den Grundsätzen der Datenminimierung und Vertraulichkeit behandelt.</p></section>
<section><h2>10. Rechte</h2><p>Betroffene Personen können, soweit anwendbar, Auskunft, Berichtigung, Löschung, Einschränkung, Datenübertragbarkeit, Widerspruch und den Widerruf einer Einwilligung verlangen, indem sie an <a href="mailto:contatti@splendoria.vip">contatti@splendoria.vip</a> schreiben. Die Antwort erfolgt unverzüglich und in der Regel innerhalb eines Monats. Eine Beschwerde bei der zuständigen Datenschutzaufsichtsbehörde bleibt jederzeit möglich.</p></section>
<section><h2>11. Minderjährige und Aktualisierungen</h2><p>Der Dienst richtet sich an volljährige Personen. Daten über Minderjährige dürfen nur eingegeben werden, wenn der Nutzer dazu berechtigt ist und nur soweit dies unbedingt erforderlich ist. Diese Hinweise werden aktualisiert, wenn sich der Dienst, die Anbieter oder die anwendbaren Vorschriften ändern.</p></section>
</div></article>`,
    en: `<article class="legal-page"><header class="legal-hero"><div class="legal-reading"><p class="eyebrow">Personal data protection</p><h1>Privacy Policy</h1><p>Information provided under Articles 12 and 13 of Regulation (EU) 2016/679. We explain clearly what data we process, why we process it and how long we keep it.</p><p class="legal-updated">Last updated: 29 August 2026</p></div></header><div class="legal-reading legal-content">
<section><h2>1. Data controller</h2><p>The data controller is <strong>AI Arena di Raoul Ragazzi</strong>, VAT number 02950290219, Via Goethe 42, Merano and Via Settala 1, Milan, Italy. For privacy matters, exercise of rights or reports: <a href="mailto:contatti@splendoria.vip">contatti@splendoria.vip</a>.</p></section>
<section><h2>2. Data we process</h2><ul><li>account, contact, authentication and security data;</li><li>commercial requests, orders and administrative data;</li><li>memories, interviews, chapters, materials and editorial preferences entered by the user;</li><li>technical data required to protect the service;</li><li>local copies of drafts stored in the browser on the user’s device to protect against accidental loss.</li></ul><p>Splendoria does not sell personal data and does not use it for behavioural advertising or commercial profiling.</p></section>
<section><h2>3. Purposes and legal bases</h2><div class="legal-table-wrap"><table><thead><tr><th>Purpose</th><th>Legal basis</th></tr></thead><tbody><tr><td>Account, Studio, writing, assistance and delivery of the service</td><td>Contract or pre-contractual measures, Article 6(1)(b) GDPR</td></tr><tr><td>Contacts, quotations and requests</td><td>Pre-contractual measures and legitimate interest in responding, Articles 6(1)(b) and 6(1)(f) GDPR</td></tr><tr><td>Billing and administrative obligations</td><td>Contract and legal obligations, Articles 6(1)(b) and 6(1)(c) GDPR</td></tr><tr><td>Security, abuse prevention and protection of rights</td><td>Legitimate interest, Article 6(1)(f) GDPR</td></tr><tr><td>Muse and AI functions requested by the user</td><td>Performance of the requested service, Article 6(1)(b) GDPR; explicit consent where the user’s special-category data are required, Article 9(2)(a) GDPR</td></tr></tbody></table></div></section>
<section><h2>4. Sensitive memories and other people’s data</h2><p>A personal story may contain special categories of personal data, such as health, religious or political beliefs, ethnic origin, sex life or sexual orientation. The user decides what to tell and should limit information to what is relevant to the project. Anyone adding information, photographs or documents concerning third parties must be entitled to use them lawfully and must respect their dignity, privacy and rights.</p></section>
<section><h2>5. Artificial intelligence and human control</h2><p>Functions called “Muse” use artificial intelligence systems to formulate questions, organise material, generate drafts and suggest revisions. The user is informed when interacting with AI, may edit or reject every output and retains control over the work. Splendoria does not make solely automated decisions producing legal or similarly significant effects on a person. More information is available on the <a href="/trasparenza-ai">AI Transparency</a> page.</p></section>
<section><h2>6. Browser safety copy</h2><p>In the Studio, text and editorial fields may also be kept in the <strong>device’s local storage for up to 365 days after the last change</strong>. This technical copy remains in the browser and is not automatically sent to Splendoria. Passwords, tokens, sessions, email addresses and files are not included. The browser or the user may delete the copy at any time.</p></section>
<section><h2>7. Recipients and transfers</h2><p>Data may be processed, to the extent necessary, by providers of cloud infrastructure, databases, security, email and AI; authorised professionals carrying out editorial review and production; advisers; and public authorities where required by law. Where processing involves a transfer outside the European Economic Area, the mechanisms provided by Chapter V GDPR are used, such as adequacy decisions or standard contractual clauses.</p></section>
<section><h2>8. Retention</h2><p>Accounts and projects are retained for the duration of the relationship and, where necessary, for subsequent statutory periods or the protection of legal rights. Sessions last no more than 30 days; password-recovery links 30 minutes; technical security and audit events up to 365 days. Local draft copies have a maximum application lifetime of 365 days from the last change unless deleted earlier from the browser.</p></section>
<section><h2>9. Security</h2><p>Splendoria applies proportionate technical and organisational measures, including encrypted connections, cryptographically derived passwords, HttpOnly and Secure session cookies, separation of access, rate limiting and logging of critical events. Editorial content is handled according to data-minimisation and confidentiality principles.</p></section>
<section><h2>10. Rights</h2><p>Where applicable, data subjects may request access, rectification, erasure, restriction, portability, objection and withdrawal of consent by writing to <a href="mailto:contatti@splendoria.vip">contatti@splendoria.vip</a>. Splendoria responds without undue delay and normally within one month. Data subjects may also lodge a complaint with the competent data-protection supervisory authority.</p></section>
<section><h2>11. Minors and updates</h2><p>The service is intended for adults. Data concerning minors may be entered only where the user is entitled to do so and only to the extent strictly necessary. This notice is updated when the service, providers or applicable law change.</p></section>
</div></article>`
  },
  cookies: {
    de: `<article class="legal-page"><header class="legal-hero"><div class="legal-reading"><p class="eyebrow">Cookies und lokale Technologien</p><h1>Cookie-Richtlinie</h1><p>Splendoria verwendet ausschließlich technische Werkzeuge, die für den Dienst erforderlich sind. Keine Werbung, kein Profiling, keine Social-Media-Tracker.</p><p class="legal-updated">Letzte Aktualisierung: 29. August 2026</p></div></header><div class="legal-reading legal-content">
<section><h2>1. Kurz erklärt</h2><p>Cookies sind kleine Kennungen, die vom Browser gespeichert werden. Ähnliche Technologien wie Local Storage können Präferenzen oder Entwürfe direkt auf dem Gerät speichern. Technisch erforderliche Werkzeuge können ohne vorherige Einwilligung eingesetzt werden; für etwaige nicht notwendige Werkzeuge wird Splendoria zuvor eine freiwillige, spezifische und widerrufliche Einwilligung einholen.</p></section>
<section><h2>2. Verwendete Werkzeuge</h2><div class="legal-table-wrap"><table><thead><tr><th>Name</th><th>Art und Zweck</th><th>Dauer</th></tr></thead><tbody><tr><td><code>spl_session</code></td><td>Technisches First-Party-Cookie. Hält die Anmeldung aufrecht und schützt die Sitzung; HttpOnly, Secure und SameSite=Lax.</td><td>Höchstens 30 Tage; beim Abmelden gelöscht</td></tr><tr><td><code>splendoria-voice-language</code></td><td>Technischer Local Storage. Speichert die für die Diktierfunktion gewählte Sprache.</td><td>Bis zur Änderung oder Löschung im Browser</td></tr><tr><td><code>splendoria-cookie-notice-v2</code></td><td>Technischer Local Storage. Merkt, dass der kurze Datenschutzhinweis geschlossen wurde.</td><td>Bis zur nächsten wesentlichen Version oder Löschung im Browser</td></tr><tr><td><code>splendoria:client-draft:v1:&lt;Seite&gt;</code></td><td>Technischer Local Storage. Lokale Sicherungskopie redaktioneller Felder im Studio. Sie enthält keine Passwörter, Token, Sitzungen, E-Mail-Adressen oder Dateien und wird nicht automatisch an den Server gesendet.</td><td>Bis zu 365 Tage nach der letzten Änderung</td></tr></tbody></table></div></section>
<section><h2>3. Warum wir nicht um „Alle akzeptieren“ bitten</h2><p>In der aktuellen Konfiguration gibt es keine Werbe-, Profiling- oder Drittanbieter-Analytics-Cookies. Um Einwilligung für nicht vorhandene Tracker zu bitten, wäre unnötig und intransparent. Der kleine Hinweis dient daher ausschließlich der Information. Sollten künftig nicht notwendige Werkzeuge eingeführt werden, bleiben sie deaktiviert, bis der Nutzer vorher eine Wahl getroffen hat; Ablehnen und Akzeptieren werden gleichwertig angeboten.</p></section>
<section><h2>4. Lokale Entwurfskopien</h2><p>Um das Risiko versehentlichen Datenverlusts zu reduzieren, kann das Studio bis zu 12 Monate lang eine lokale Kopie von Texten und redaktionellen Feldern auf dem Gerät speichern. Soweit verfügbar, bittet Splendoria den Browser, diesen Speicher als persistent zu behandeln; der Browser behält jedoch die Kontrolle und kann Daten aufgrund von Nutzereinstellungen, privatem Modus oder Speicherbedarf löschen.</p></section>
<section><h2>5. Cookies und lokale Daten verwalten</h2><p>Cookies und Local Storage können jederzeit im Browser gelöscht werden. Das Löschen von <code>spl_session</code> führt zur Abmeldung; das Löschen lokaler Entwürfe entfernt keine Version, die gegebenenfalls bereits auf Splendoria-Servern gespeichert wurde. Mikrofon- und Diktierberechtigungen werden separat in den Browsereinstellungen verwaltet.</p></section>
<section><h2>6. Kein websiteübergreifendes Tracking</h2><p>Splendoria verwendet die oben genannten Werkzeuge nicht, um Werbeprofile zu erstellen, Nutzer über verschiedene Websites hinweg zu verfolgen oder die Nutzung verschiedener Geräte zu kommerziellen Zwecken miteinander zu verknüpfen.</p></section>
<section><h2>7. Verantwortlicher und Rechte</h2><p>Verantwortlicher: AI Arena di Raoul Ragazzi, Partita IVA 02950290219, Via Goethe 42, Meran und Via Settala 1, Mailand. Kontakt: <a href="mailto:contatti@splendoria.vip">contatti@splendoria.vip</a>. Zwecke, Rechtsgrundlagen, Empfänger und Rechte sind in der <a href="/privacy-policy">Datenschutzerklärung</a> beschrieben.</p></section>
</div></article>`,
    en: `<article class="legal-page"><header class="legal-hero"><div class="legal-reading"><p class="eyebrow">Cookies and local technologies</p><h1>Cookie Policy</h1><p>Splendoria uses only technical tools required to provide the service. No advertising, no profiling, no social trackers.</p><p class="legal-updated">Last updated: 29 August 2026</p></div></header><div class="legal-reading legal-content">
<section><h2>1. In brief</h2><p>Cookies are small identifiers stored by the browser. Similar technologies, such as local storage, can remember preferences or drafts directly on the device. Strictly necessary technical tools may be used without prior consent; if non-essential tools are introduced, Splendoria will first ask for consent that is freely given, specific and revocable.</p></section>
<section><h2>2. Tools used</h2><div class="legal-table-wrap"><table><thead><tr><th>Name</th><th>Type and purpose</th><th>Duration</th></tr></thead><tbody><tr><td><code>spl_session</code></td><td>First-party technical cookie. Keeps the account signed in and protects the session; HttpOnly, Secure and SameSite=Lax.</td><td>Up to 30 days; deleted on logout</td></tr><tr><td><code>splendoria-voice-language</code></td><td>Technical local storage. Remembers the language selected for dictation.</td><td>Until changed or deleted in the browser</td></tr><tr><td><code>splendoria-cookie-notice-v2</code></td><td>Technical local storage. Remembers that the short privacy notice has been closed.</td><td>Until the next material version or deletion in the browser</td></tr><tr><td><code>splendoria:client-draft:v1:&lt;page&gt;</code></td><td>Technical local storage. Local safety copy of editorial fields in the Studio. It does not include passwords, tokens, sessions, email addresses or files and is not automatically sent to the server.</td><td>Up to 365 days after the last change</td></tr></tbody></table></div></section>
<section><h2>3. Why we do not ask you to “Accept all”</h2><p>The current configuration contains no advertising, profiling or third-party analytics cookies. Asking for consent to trackers that do not exist would be unnecessary and misleading. The small banner is therefore informational only. If non-essential tools are introduced in the future, they will remain disabled until the user makes a prior choice, with an equivalent option to reject or accept them.</p></section>
<section><h2>4. Local draft copies</h2><p>To reduce the risk of accidental loss, the Studio may keep a local copy of text and editorial fields on the device for up to 12 months. Where available, Splendoria asks the browser to treat this storage as persistent; the browser remains in control and may remove it because of user settings, private browsing or storage requirements.</p></section>
<section><h2>5. Managing cookies and local data</h2><p>Cookies and local storage can be deleted from the browser at any time. Deleting <code>spl_session</code> signs the user out; deleting local drafts does not remove any version already saved on Splendoria’s servers. Microphone and dictation permissions are managed separately in the browser settings.</p></section>
<section><h2>6. No cross-site tracking</h2><p>Splendoria does not use the tools listed above to create advertising profiles, follow users across different websites or combine activity across devices for commercial purposes.</p></section>
<section><h2>7. Controller and rights</h2><p>Controller: AI Arena di Raoul Ragazzi, VAT number 02950290219, Via Goethe 42, Merano and Via Settala 1, Milan, Italy. Contact: <a href="mailto:contatti@splendoria.vip">contatti@splendoria.vip</a>. Purposes, legal bases, recipients and rights are described in the <a href="/privacy-policy">Privacy Policy</a>.</p></section>
</div></article>`
  },
  terms: {
    de: `<article class="legal-page"><header class="legal-hero"><div class="legal-reading"><p class="eyebrow">Nutzungs- und Verkaufsbedingungen</p><h1>Allgemeine Geschäftsbedingungen</h1><p>Regeln für die Nutzung des Studios und für Anfragen zu den Splendoria-Leistungen.</p><p class="legal-updated">Letzte Aktualisierung: 12. August 2026</p></div></header><div class="legal-reading legal-content">
<section><h2>1. Anbieter des Dienstes</h2><p>Splendoria ist ein Dienst von <strong>AI Arena di Raoul Ragazzi</strong>, Partita IVA <strong>02950290219</strong>, mit Anschrift in <strong>Via Goethe 42, Meran und Via Settala 1, Mailand</strong>, erreichbar unter <a href="mailto:contatti@splendoria.vip">contatti@splendoria.vip</a>.</p></section>
<section><h2>2. Gegenstand</h2><p>Splendoria bietet einen digitalen Prozess, um Erinnerungen und Materialien zu sammeln, Interviews durchzuführen, ein Werk zu strukturieren und zu schreiben sowie Überarbeitung, Layout, Umschlag, digitale Version und weitere in der gewählten Edition bezeichnete Leistungen vorzubereiten. Die Muse unterstützt mithilfe künstlicher Intelligenz; menschliche Aufsicht ist Bestandteil der beschriebenen Methode.</p></section>
<section><h2>3. Konto und erstes Kapitel</h2><p>Der Nutzer muss richtige Angaben machen, seine Zugangsdaten schützen und unbefugte Zugriffe unverzüglich melden. Das Konto ist persönlich. Eine etwaige kostenlose Testphase ist auf die auf der Website genannten Funktionen und Mengen begrenzt und darf nicht missbräuchlich oder automatisiert genutzt werden.</p></section>
<section><h2>4. Editionen, Preise und Zusatzleistungen</h2><p>Inhalte, Richtwerte und Preise der Editionen ergeben sich aus der zum Zeitpunkt der Anfrage geltenden Preisliste. Die Seitenzahl kann je nach Layout und Material variieren. Zusätzliche Exemplare, Übersetzungen, grafische Arbeiten oder Sonderwünsche werden gesondert angeboten. Steuerliche Behandlung, Zahlungsweise und Zahlungsfristen werden in der Bestätigung oder im Vertragsangebot angegeben.</p></section>
<section><h2>5. Vertragsschluss</h2><p>Das Absenden eines Formulars oder die Auswahl einer Edition im Studio ist eine Anfrage des Nutzers und löst nicht automatisch die Bearbeitung aus. Der Vertrag kommt mit der schriftlichen Bestätigung von Splendoria zustande; diese fasst Edition, Leistungen, Vergütung, voraussichtliche Zeiten und anwendbare Bedingungen zusammen. Das Projekt beginnt wie vereinbart und, soweit vorgesehen, nach Eingang der erforderlichen Zahlung.</p></section>
<section><h2>6. Widerrufsrecht von Verbrauchern</h2><p>Soweit anwendbar, kann ein Verbraucher innerhalb von 14 Tagen nach Vertragsschluss durch eine eindeutige Erklärung an <a href="mailto:contatti@splendoria.vip">contatti@splendoria.vip</a> widerrufen. Verlangt er ausdrücklich, dass die Dienstleistung während dieser Frist beginnt, kann bei einem Widerruf ein anteiliger Betrag für bereits erbrachte Leistungen geschuldet sein. Das Widerrufsrecht kann nach vollständiger Erbringung der Dienstleistung nur mit der vorherigen ausdrücklichen Zustimmung und der gesetzlich vorgeschriebenen Kenntnisnahme erlöschen. Ausnahmen für nach Kundenspezifikation angefertigte Waren oder digitale Inhalte gelten ausschließlich in den gesetzlich vorgesehenen Fällen und unter den dort genannten Voraussetzungen und werden vor Beginn oder Bereitstellung der betroffenen Leistung hervorgehoben.</p></section>
<section><h2>7. Materialien und Verantwortung des Nutzers</h2><p>Der Nutzer gewährleistet, dass er die bereitgestellten Texte, Fotografien, Dokumente, Namen und Informationen verwenden und teilen darf. Rechtswidrige, verleumderische, diskriminierende oder die Privatsphäre bzw. Rechte Dritter verletzende Inhalte sind zu vermeiden. Splendoria kann die Bearbeitung aussetzen und Änderungen verlangen, wenn rechtliche oder ethische Risiken erkennbar werden.</p></section>
<section><h2>8. Künstliche Intelligenz und Freigabe</h2><p>Der Nutzer wird darüber informiert, dass die Muse künstliche Intelligenz einsetzt, um Fragen, Strukturen, Entwürfe und Überarbeitungen zu erzeugen. Ausgaben können Ungenauigkeiten enthalten und werden nicht veröffentlicht oder als endgültig geliefert, ohne einen Prüf- und Freigabeprozess zu durchlaufen. Die Technologie ersetzt nicht das Urteil des Autors, des Nutzers oder der menschlichen Aufsicht.</p></section>
<section><h2>9. Geistiges Eigentum</h2><p>Der Nutzer behält die Rechte an den von ihm bereitgestellten Originalmaterialien und räumt Splendoria eine begrenzte, nicht ausschließliche und für die Durchführung des Projekts erforderliche Lizenz ein. Rechte am fertigen Werk und Nutzungsbefugnisse richten sich nach der Vertragsbestätigung und dem Urheberrecht. Marken, Software, Schnittstellen, Methode und allgemeine Splendoria-Materialien verbleiben bei den jeweiligen Rechteinhabern.</p></section>
<section><h2>10. Überarbeitungen, Freigabe und Lieferung</h2><p>Der Nutzer wirkt mit, indem er Materialien und Rückmeldungen innerhalb angemessener Fristen bereitstellt. Umfang von Überarbeitungen, Formate und enthaltene Exemplare richten sich nach der Edition. Fristen beginnen, sobald die erforderlichen Materialien, Zahlungen und Freigaben vorliegen; Verzögerungen durch zusätzliche Wünsche oder ausstehende Rückmeldungen können den Zeitplan verändern.</p></section>
<section><h2>11. Haftung</h2><p>Splendoria erbringt den Dienst mit professioneller Sorgfalt. Splendoria haftet nicht für Tatsachen, Rechte oder Genehmigungen im Zusammenhang mit vom Nutzer bereitgestellten Materialien oder für Nichtverfügbarkeit infolge höherer Gewalt oder Drittleistungen außerhalb der angemessenen Kontrolle von Splendoria. Zwingende Haftungsvorschriften und Verbraucherrechte bleiben unberührt.</p></section>
<section><h2>12. Sperrung und Schließung</h2><p>Der Verantwortliche kann Konten einschränken oder sperren, wenn sie gegen das Gesetz, diese Bedingungen oder die Sicherheit des Dienstes verstoßen; der Nutzer wird soweit möglich informiert. Der Nutzer kann sein Konto im geschützten Bereich nach einer verstärkten Bestätigung mit dem Passwort selbst schließen. Die Löschung entfernt Zugang und narrative Inhalte; gesetzliche Aufbewahrungspflichten, laufende Vertragsverhältnisse und Verwaltungsunterlagen, die anonymisiert oder minimiert aufzubewahren sind, bleiben unberührt.</p></section>
<section><h2>13. Anwendbares Recht und Streitigkeiten</h2><p>Es gilt italienisches Recht, unbeschadet zwingender Verbraucherschutzvorschriften. Die örtliche Zuständigkeit bestimmt sich nach den anwendbaren Vorschriften; für Verbraucher bleibt, soweit gesetzlich vorgesehen, das Gericht am Wohnsitz oder gewöhnlichen Aufenthalt zuständig.</p></section>
<section><h2>14. Änderungen</h2><p>Änderungen gelten für die Zukunft und werden mit dem Aktualisierungsdatum veröffentlicht. Für bereits bestätigte Projekte gelten die angenommenen Bedingungen weiter, sofern nicht zwingende gesetzliche Änderungen oder schriftliche Vereinbarungen etwas anderes vorsehen.</p></section>
</div></article>`,
    en: `<article class="legal-page"><header class="legal-hero"><div class="legal-reading"><p class="eyebrow">Terms of use and sale</p><h1>Terms and Conditions</h1><p>Rules applying to use of the Studio and to requests concerning Splendoria services.</p><p class="legal-updated">Last updated: 12 August 2026</p></div></header><div class="legal-reading legal-content">
<section><h2>1. Service provider</h2><p>Splendoria is a service provided by <strong>AI Arena di Raoul Ragazzi</strong>, VAT number <strong>02950290219</strong>, with geographical address at <strong>Via Goethe 42, Merano and Via Settala 1, Milan, Italy</strong>, contactable at <a href="mailto:contatti@splendoria.vip">contatti@splendoria.vip</a>.</p></section>
<section><h2>2. Scope</h2><p>Splendoria provides a digital process for collecting memories and materials, conducting interviews, organising and writing a work, and preparing revision, layout, cover, digital edition and the other services stated in the selected plan. The Muse provides assistance through artificial intelligence; human oversight is part of the stated method.</p></section>
<section><h2>3. Account and first chapter</h2><p>The user must provide accurate information, safeguard credentials and promptly report unauthorised access. The account is personal. Any free trial is limited to the functions and quantities stated on the website and must not be used abusively or through automation.</p></section>
<section><h2>4. Plans, prices and additional services</h2><p>Contents, indicative limits and plan prices are described in the price list in force when the request is made. Page counts may vary according to layout and materials. Additional copies, translations, graphic work or special requests are quoted separately. Applicable tax treatment, payment methods and payment deadlines are specified in the written confirmation or contractual proposal.</p></section>
<section><h2>5. Formation of the contract</h2><p>Submitting a form or selecting a plan in the Studio constitutes a request by the user and does not automatically start production. The contract is formed when Splendoria sends written confirmation summarising the plan, services, price, indicative timing and applicable conditions. The project begins as agreed and, where applicable, after the required payment has been received.</p></section>
<section><h2>6. Consumer right of withdrawal</h2><p>Where applicable, a consumer may withdraw within 14 days of entering into the contract by sending an explicit statement to <a href="mailto:contatti@splendoria.vip">contatti@splendoria.vip</a>. If the consumer expressly asks for the service to begin during that period, a proportionate amount for services already performed may be due in the event of withdrawal. The right may cease after full performance of the service only with the consumer’s prior express consent and acknowledgement as required by law. Exceptions for made-to-measure goods or digital content apply only in the cases and subject to the conditions laid down by law and will be highlighted before the relevant work or supply begins.</p></section>
<section><h2>7. Materials and user responsibility</h2><p>The user warrants that they may use and share the texts, photographs, documents, names and information supplied. The user must avoid unlawful, defamatory, discriminatory content or material that infringes privacy or third-party rights. Splendoria may suspend work and request changes where legal or ethical risks emerge.</p></section>
<section><h2>8. Artificial intelligence and approval</h2><p>The user is informed that the Muse uses artificial intelligence to generate questions, structures, drafts and revisions. Outputs may contain inaccuracies and are not published or delivered as final without a verification and approval process. Technology does not replace the judgement of the author, user or human supervisor.</p></section>
<section><h2>9. Intellectual property</h2><p>The user retains rights in the original materials supplied and grants Splendoria a limited, non-exclusive licence solely to carry out the project. Rights in the final work and rights of use are governed by the contractual confirmation and copyright law. Splendoria trademarks, software, interfaces, method and general materials remain the property of their respective rights holders.</p></section>
<section><h2>10. Revisions, approval and delivery</h2><p>The user cooperates by supplying materials and feedback within reasonable timeframes. Revisions, formats and included copies depend on the selected plan. Timelines run from the availability of the necessary materials, payments and approvals; delays caused by additional requests or missing feedback may change the schedule.</p></section>
<section><h2>11. Liability</h2><p>Splendoria undertakes to provide the service with professional care. It is not responsible for facts, rights or permissions concerning materials supplied by the user, nor for unavailability caused by force majeure or third-party services outside its reasonable control. Mandatory liability rules and statutory consumer rights remain unaffected.</p></section>
<section><h2>12. Suspension and closure</h2><p>The controller may restrict or suspend accounts used in breach of law, these terms or service security, informing the user where possible. The user may close the account from the private area after enhanced password confirmation. Deletion removes access and narrative content; statutory retention duties, any ongoing contractual relationship and administrative documentation that must be retained in anonymised or minimised form remain unaffected.</p></section>
<section><h2>13. Governing law and disputes</h2><p>Italian law applies, without prejudice to mandatory consumer protections. Territorial jurisdiction is determined under the applicable rules; for consumers, the court of the consumer’s residence or domicile remains competent where provided by law.</p></section>
<section><h2>14. Changes</h2><p>Changes apply for the future and are published with the date of the update. For projects already confirmed, the accepted conditions continue to apply unless mandatory changes in law or written agreements require otherwise.</p></section>
</div></article>`
  },
  notice: {
    de: `<article class="legal-page"><header class="legal-hero"><div class="legal-reading"><p class="eyebrow">Informationen zur Website</p><h1>Impressum und rechtliche Hinweise</h1><p>Anbieterkennzeichnung, Rechte an Inhalten und Nutzungsgrenzen der Website Splendoria.</p><p class="legal-updated">Letzte Aktualisierung: 12. August 2026</p></div></header><div class="legal-reading legal-content">
<section><h2>Identität und Kontakt</h2><p>Anbieter und Betreiber der Website: <strong>AI Arena di Raoul Ragazzi</strong><br>Partita IVA: <strong>02950290219</strong><br>Anschrift: <strong>Via Goethe 42, Meran und Via Settala 1, Mailand</strong><br>E-Mail: <a href="mailto:contatti@splendoria.vip">contatti@splendoria.vip</a><br>Domain: <a href="https://www.splendoria.vip">www.splendoria.vip</a></p></section>
<section><h2>Zweck der Website</h2><p>Die Website stellt Splendoria vor, ermöglicht Informationsanfragen, die Einrichtung eines persönlichen Studios und den Beginn redaktioneller Projekte. Die kommerziellen Informationen werden mit Sorgfalt formuliert; der endgültige Leistungsumfang ergibt sich jedoch aus der Vertragsbestätigung.</p></section>
<section><h2>Geistiges Eigentum</h2><p>Name, Marke, Gestaltung, institutionelle Texte, Struktur, Software und Methode von Splendoria dürfen ohne Genehmigung nicht über das gesetzlich Zulässige hinaus kopiert, verbreitet oder verwendet werden. Rechte der Nutzer an von ihnen bereitgestellten Materialien und Rechte Dritter bleiben unberührt.</p></section>
<section><h2>Verfügbarkeit und Sicherheit</h2><p>Der Betreiber trifft angemessene Maßnahmen, um den Dienst verfügbar und sicher zu halten, kann jedoch keine absolute Kontinuität garantieren. Wartung, Aktualisierungen, höhere Gewalt oder die Nichtverfügbarkeit von Dienstleistern können vorübergehende Unterbrechungen verursachen.</p></section>
<section><h2>Künstliche Intelligenz</h2><p>Als „Muse“, „Muse AI“ oder ähnlich bezeichnete Funktionen verwenden künstliche Intelligenz. Die Ausgaben dienen der Unterstützung, können Fehler enthalten und müssen geprüft werden. Weitere Informationen finden Sie auf der Seite <a href="/trasparenza-ai">KI-Transparenz</a>.</p></section>
<section><h2>Links und Inhalte Dritter</h2><p>Externe Links werden gegebenenfalls als Service bereitgestellt. Inhalte, Verfügbarkeit und Datenverarbeitung dieser Angebote liegen in der Verantwortung der jeweiligen Betreiber.</p></section>
</div></article>`,
    en: `<article class="legal-page"><header class="legal-hero"><div class="legal-reading"><p class="eyebrow">Website information</p><h1>Legal Notice</h1><p>Provider identity, content ownership and limits on use of the Splendoria website.</p><p class="legal-updated">Last updated: 12 August 2026</p></div></header><div class="legal-reading legal-content">
<section><h2>Identity and contact details</h2><p>Service provider and website operator: <strong>AI Arena di Raoul Ragazzi</strong><br>VAT number: <strong>02950290219</strong><br>Geographical address: <strong>Via Goethe 42, Merano and Via Settala 1, Milan, Italy</strong><br>Email: <a href="mailto:contatti@splendoria.vip">contatti@splendoria.vip</a><br>Domain: <a href="https://www.splendoria.vip">www.splendoria.vip</a></p></section>
<section><h2>Purpose of the website</h2><p>The website presents Splendoria, allows visitors to request information, create a personal Studio and begin editorial projects. Commercial information is prepared with care, but the definitive scope of the service is the one stated in the contractual confirmation.</p></section>
<section><h2>Intellectual property</h2><p>The Splendoria name, trademark, visual design, institutional copy, structure, software and method may not be copied, distributed or used beyond what is permitted by law without authorisation. Users retain rights in the materials they provide and any third-party rights remain unaffected.</p></section>
<section><h2>Availability and security</h2><p>The operator takes reasonable measures to keep the service available and secure but cannot guarantee uninterrupted availability. Maintenance, updates, force-majeure events or unavailable suppliers may cause temporary interruptions.</p></section>
<section><h2>Artificial intelligence</h2><p>Functions described as “Muse”, “Muse AI” or equivalent use artificial intelligence. Outputs are assistive, may contain errors and must be checked. Further information is available on the <a href="/trasparenza-ai">AI Transparency</a> page.</p></section>
<section><h2>Third-party links and content</h2><p>External links may be provided for convenience. Their content, availability and data processing are controlled by the respective operators.</p></section>
</div></article>`
  },
  ai: {
    de: `<article class="legal-page"><header class="legal-hero"><div class="legal-reading"><p class="eyebrow">Muse und menschliche Aufsicht</p><h1>Transparenz zur künstlichen Intelligenz</h1><p>Klare Informationen über die Rolle der KI im Splendoria-Prozess im Einklang mit den Transparenzgrundsätzen des AI Act.</p><p class="legal-updated">Letzte Aktualisierung: 12. August 2026</p></div></header><div class="legal-reading legal-content">
<section><h2>Sie interagieren mit einem System künstlicher Intelligenz</h2><p>Die Muse von Splendoria sind Funktionen künstlicher Intelligenz. Wenn Sie Fragen, eine Struktur, einen Entwurf oder eine Überarbeitung anfordern, wird ein Teil des Ergebnisses automatisch mithilfe von Modellen erzeugt oder umformuliert, die über die Splendoria-Infrastruktur bereitgestellt werden.</p></section>
<section><h2>Was die Muse tut</h2><ul><li>sie schlägt Fragen vor, um Erinnerungen und Einzelheiten hervorzubringen;</li><li>sie ordnet Informationen zu einer möglichen narrativen Struktur;</li><li>sie erstellt auf Wunsch Kapitelentwürfe;</li><li>sie schlägt grammatikalische, stilistische oder narrative Überarbeitungen vor;</li><li>sie wandelt Sprache über die Spracherkennungsfunktionen des Browsers in Text um.</li></ul></section>
<section><h2>Was sie nicht tut</h2><p>Die Muse ersetzt den Autor nicht, garantiert nicht die Richtigkeit von Tatsachen, gibt keine Rechtsberatung und trifft keine Entscheidungen mit rechtlicher Wirkung für den Nutzer. Sie verwendet weder Emotionserkennung noch biometrische Kategorisierung oder Systeme zur Bewertung von Personen.</p></section>
<section><h2>Nutzerkontrolle und menschliche Aufsicht</h2><p>Jeder Text bleibt bearbeitbar. Der Nutzer kann Ausgaben korrigieren, ablehnen oder neu erzeugen und behält die Kontrolle über seine Geschichte. Vor der endgültigen Lieferung durchläuft das Werk die menschliche Aufsicht und professionelle Überarbeitung, die in der erworbenen Edition vorgesehen sind.</p></section>
<section><h2>Grenzen und verantwortungsvolle Nutzung</h2><p>Generative Systeme können plausible, aber unzutreffende Formulierungen erzeugen, Kontext auslassen oder nicht bestätigte Details hinzufügen. Der Nutzer muss Namen, Daten, Zitate, Tatsachen und Angaben über Dritte prüfen. Splendoria setzt Anweisungen ein, die die Stimme des Autors bewahren und Erfindungen reduzieren sollen; menschliche Kontrolle bleibt dennoch wesentlich.</p></section>
<section><h2>Daten und Diktierfunktion</h2><p>Eingegebene Inhalte werden gemäß der <a href="/privacy-policy">Datenschutzerklärung</a> zur Bereitstellung der angeforderten Funktionen verwendet. Splendoria speichert die Audiodaten der Diktierfunktion nicht absichtlich; der Browser wandelt Sprache entsprechend den Fähigkeiten und Bedingungen des jeweiligen Anbieters in Text um.</p></section>
<section><h2>Kontakt</h2><p>Um problematische Ausgaben zu melden oder Fragen zur Funktionsweise der Muse zu stellen: <a href="mailto:contatti@splendoria.vip">contatti@splendoria.vip</a>.</p></section>
</div></article>`,
    en: `<article class="legal-page"><header class="legal-hero"><div class="legal-reading"><p class="eyebrow">Muse and human oversight</p><h1>Artificial Intelligence Transparency</h1><p>Clear information about the role of AI in the Splendoria process, in line with the transparency principles of the AI Act.</p><p class="legal-updated">Last updated: 12 August 2026</p></div></header><div class="legal-reading legal-content">
<section><h2>You are interacting with an artificial intelligence system</h2><p>Splendoria’s Muse are artificial intelligence functions. When you request questions, a structure, a draft or a revision, part of the result is generated or transformed automatically using models made available through the Splendoria infrastructure.</p></section>
<section><h2>What the Muse does</h2><ul><li>suggests questions designed to bring out memories and details;</li><li>organises information into a possible narrative structure;</li><li>generates chapter drafts on request;</li><li>suggests grammatical, stylistic or narrative revisions;</li><li>turns speech into text using the browser’s speech-recognition functions.</li></ul></section>
<section><h2>What it does not do</h2><p>The Muse does not replace the author, does not guarantee factual accuracy, does not provide legal advice and does not make decisions producing legal effects for the user. It does not use emotion recognition, biometric categorisation or systems for rating people.</p></section>
<section><h2>User control and human oversight</h2><p>Every text remains editable. The user may correct, reject or regenerate outputs and keeps control of their own story. Before final delivery, the work goes through the human oversight and professional review included in the purchased plan.</p></section>
<section><h2>Limitations and responsible use</h2><p>Generative systems may produce plausible but inaccurate wording, omit context or introduce unconfirmed details. Users must verify names, dates, quotations, facts and information concerning third parties. Splendoria applies instructions designed to preserve the author’s voice and reduce inventions, but human review remains essential.</p></section>
<section><h2>Data and dictation</h2><p>Content entered by the user is used to provide the requested functions in accordance with the <a href="/privacy-policy">Privacy Policy</a>. Splendoria does not intentionally retain dictation audio; the browser turns speech into text according to the capabilities and conditions of the relevant provider.</p></section>
<section><h2>Contact</h2><p>To report a problematic output or ask for clarification about how the Muse works: <a href="mailto:contatti@splendoria.vip">contatti@splendoria.vip</a>.</p></section>
</div></article>`
  }
};

function replaceMain(html, body) {
  const re = /<main id="main-content" tabindex="-1">[\s\S]*?<\/main>/i;
  if (!re.test(html)) throw new Error('Splendoria legal main anchor not found');
  return html.replace(re, `<main id="main-content" tabindex="-1">${body}</main>`);
}

function pageLinks(locale) {
  return {
    '/': `/${locale}/`,
    '/#metodo': `/${locale}/#metodo`,
    '/#formule': `/${locale}/#formule`,
    '/#contatti': `/${locale}/#contatti`,
    '/guida': locale === 'de' ? '/de/leitfaden' : '/en/guide',
    '/privacy-policy': LEGAL_PATHS.privacy[locale],
    '/cookie-policy': LEGAL_PATHS.cookies[locale],
    '/termini-condizioni': LEGAL_PATHS.terms[locale],
    '/note-legali': LEGAL_PATHS.notice[locale],
    '/trasparenza-ai': LEGAL_PATHS.ai[locale]
  };
}

export const LEGAL_PAGES = Object.entries(LEGAL_PATHS).map(([key, paths]) => ({
  key,
  basePath: paths.it,
  paths,
  localize(html, locale) {
    let localized = replaceMain(html, BODIES[key][locale]);
    localized = applyTextMap(localized, CHROME[locale]);
    localized = applyAttributeMap(localized, ATTRS[locale]);
    localized = localizePublicSeo(localized, locale, META[key][locale], paths);
    localized = rewriteExactHrefs(localized, pageLinks(locale));
    return localized;
  }
}));
