import { applyAttributeMap, applyTextMap, localizePublicSeo, rewriteExactHrefs } from './i18n-page-utils.js';

export const GUIDE_PATHS = { it: '/guida', de: '/de/leitfaden', en: '/en/guide' };

const META = {
  de: {
    title: 'Leitfaden zum Studio — Splendoria',
    description: 'Der praktische Splendoria-Leitfaden: Erinnerungen vorbereiten, die Muse nutzen, Kapitel verfassen, überarbeiten, speichern und die kostenlose Testphase verstehen.'
  },
  en: {
    title: 'Studio Guide — Splendoria',
    description: 'The practical Splendoria guide: prepare memories, use the Muse, write and revise chapters, save your work and understand the free trial.'
  }
};

const COMMON_DE = [
  ['Guida allo Studio — Splendoria', 'Leitfaden zum Studio — Splendoria'],
  ['Come funziona', 'So funktioniert es'], ['Listino', 'Preise'], ['Guida', 'Leitfaden'], ['Contattaci', 'Kontakt'], ['Il mio Studio', 'Mein Studio'],
  ['Manuale pratico', 'Praktischer Leitfaden'], ['Il tuo libro, un passo alla volta', 'Ihr Buch, Schritt für Schritt'],
  ['Questa guida ti accompagna senza conoscenze tecniche: raccogli i fatti, lascia che la Musa ti intervisti, crea l’indice, scrivi e rileggi il primo capitolo.', 'Dieser Leitfaden begleitet Sie ohne technische Vorkenntnisse: Sammeln Sie die Fakten, lassen Sie sich von der Muse interviewen, erstellen Sie die Gliederung, schreiben Sie und lesen Sie das erste Kapitel noch einmal durch.'],
  ['Crea lo Studio gratuito', 'Kostenloses Studio erstellen'], ['Stampa o salva la guida in PDF', 'Leitfaden drucken oder als PDF speichern'], ['Vai direttamente', 'Direkt zu'],
  ['Cominciare', 'Beginnen'], ['Preparare i ricordi', 'Erinnerungen vorbereiten'], ['Usare la Musa', 'Die Muse nutzen'], ['Rivedere il testo', 'Text überarbeiten'], ['Capire la prova', 'Testphase verstehen'], ['Risolvere i problemi', 'Probleme lösen'],
  ['Passo 1', 'Schritt 1'], ['Crea il progetto', 'Projekt anlegen'], ['Registrati con nome, email e una password di almeno dieci caratteri.', 'Registrieren Sie sich mit Namen, E-Mail-Adresse und einem Passwort mit mindestens zehn Zeichen.'],
  ['Nello Studio inserisci un titolo provvisorio, scegli il genere e la struttura da 12 o 18 capitoli.', 'Geben Sie im Studio einen vorläufigen Titel ein und wählen Sie Genre sowie eine Struktur mit 12 oder 18 Kapiteln.'],
  ['Apri il progetto. Titolo, tono e pubblico potranno essere cambiati in seguito.', 'Öffnen Sie das Projekt. Titel, Tonalität und Zielpublikum können später geändert werden.'],
  ['Non serve avere già scritto un testo.', 'Sie müssen noch keinen Text geschrieben haben.'], ['Puoi iniziare da ricordi sparsi, oppure usare la dettatura se preferisci raccontare a voce.', 'Sie können mit einzelnen Erinnerungen beginnen oder die Diktierfunktion nutzen, wenn Sie lieber erzählen als tippen.'],
  ['Passo 2', 'Schritt 2'], ['Affida fatti sufficienti', 'Genügend konkrete Fakten bereitstellen'],
  ['La Musa non deve inventare la tua vita. Prima di chiederle un capitolo, inserisci almeno circa 260–460 parole di materiale concreto e vario, in base alla lunghezza prevista.', 'Die Muse darf Ihr Leben nicht erfinden. Bevor Sie ein Kapitel anfordern, geben Sie – abhängig von der geplanten Länge – ungefähr 260 bis 460 Wörter konkretes und abwechslungsreiches Ausgangsmaterial ein.'],
  ['Persone:', 'Personen:'], ['nomi, ruoli, relazioni e caratteristiche realmente ricordate.', 'Namen, Rollen, Beziehungen und tatsächlich erinnerte Eigenschaften.'],
  ['Tempo e luoghi:', 'Zeit und Orte:'], ['anni, periodi, città, case, ambienti.', 'Jahre, Zeiträume, Städte, Häuser und Umgebungen.'],
  ['Azioni e conseguenze:', 'Handlungen und Folgen:'], ['che cosa accadde, chi fece cosa e che cosa cambiò.', 'Was geschah, wer was tat und was sich dadurch veränderte.'],
  ['Parole ricordate:', 'Erinnerte Worte:'], ['usa le virgolette solo per dialoghi realmente forniti.', 'Setzen Sie Anführungszeichen nur bei Dialogen, die tatsächlich überliefert wurden.'],
  ['Senso:', 'Bedeutung:'], ['che cosa hai compreso e che cosa vuoi lasciare al lettore.', 'Was Sie verstanden haben und was Sie dem Leser mitgeben möchten.'],
  ['Se le informazioni non bastano, Splendoria non sostituisce il capitolo con un testo generico: ti chiede di aggiungere altri dati o di completare l’intervista.', 'Wenn die Informationen nicht ausreichen, ersetzt Splendoria das Kapitel nicht durch einen allgemeinen Text: Sie werden gebeten, weitere Angaben hinzuzufügen oder das Interview zu vervollständigen.'],
  ['Passi 3–5', 'Schritte 3–5'], ['Dall’intervista al capitolo', 'Vom Interview zum Kapitel'], ['Salva i ricordi.', 'Erinnerungen speichern.'],
  ['Dopo aver confermato la liceità dei contenuti, il salvataggio automatico custodisce le modifiche mentre scrivi.', 'Nachdem Sie die Rechtmäßigkeit der Inhalte bestätigt haben, sichert die automatische Speicherung Ihre Änderungen während des Schreibens.'],
  ['Genera l’intervista.', 'Interview erstellen.'], ['Rispondi alle domande una alla volta. Puoi scrivere, dettare oppure chiedere una base alla Musa quando le fonti sono sufficienti.', 'Beantworten Sie die Fragen nacheinander. Sie können schreiben, diktieren oder – wenn genügend Quellen vorliegen – die Muse um einen Entwurf bitten.'],
  ['Disegna la trama.', 'Struktur entwerfen.'], ['“Disegna la trama del mio libro” crea l’indice completo. Rileggi i titoli prima di proseguire.', '„Die Struktur meines Buches entwerfen“ erstellt die vollständige Gliederung. Prüfen Sie die Titel, bevor Sie fortfahren.'],
  ['Apri il primo capitolo.', 'Erstes Kapitel öffnen.'], ['Scrivi direttamente oppure premi “Affidati alla Musa”. Attendi la scrittura e la rilettura finale senza chiudere la pagina.', 'Schreiben Sie selbst oder wählen Sie „Der Muse anvertrauen“. Warten Sie auf die Erstellung und abschließende Prüfung, ohne die Seite zu schließen.'],
  ['Detta', 'Diktieren'], ['Trasforma la voce in testo; se il browser non lo consente, scrivi nel campo.', 'Wandelt Sprache in Text um; falls Ihr Browser dies nicht unterstützt, schreiben Sie direkt in das Feld.'],
  ['Migliora', 'Verbessern'], ['Rende più fluido il testo già presente, senza aggiungere fatti.', 'Macht einen vorhandenen Text flüssiger, ohne neue Fakten hinzuzufügen.'],
  ['Affidati alla Musa', 'Der Muse anvertrauen'], ['Crea una nuova bozza soltanto dalle fonti autorizzate.', 'Erstellt einen neuen Entwurf ausschließlich aus den freigegebenen Quellen.'],
  ['Salva', 'Speichern'], ['Conferma subito le modifiche; l’autosalvataggio resta una protezione aggiuntiva.', 'Speichert Änderungen sofort; die automatische Speicherung bleibt eine zusätzliche Absicherung.'],
  ['Passo 6', 'Schritt 6'], ['Rileggi come autore', 'Als Autor gegenlesen'],
  ['Controlla sempre nomi, date, luoghi, citazioni, relazioni e ordine degli eventi. Poi usa', 'Prüfen Sie immer Namen, Daten, Orte, Zitate, Beziehungen und die Reihenfolge der Ereignisse. Verwenden Sie anschließend'],
  ['“Correggi grammatica”', '„Grammatik korrigieren“'], [': il revisore interviene su ortografia, sintassi, concordanze, reggenze e punteggiatura, conservando fatti e voce.', ': Die Überarbeitung korrigiert Rechtschreibung, Syntax, Grammatik und Zeichensetzung, ohne Fakten und Stimme zu verändern.'],
  ['Splendoria applica un controllo specifico sugli ausiliari italiani: scrive, per esempio,', 'Splendoria wendet im Italienischen eine spezielle Kontrolle der Hilfsverben an und schreibt zum Beispiel'],
  ['“siamo usciti”', '„siamo usciti“'], ['“siamo andati”', '„siamo andati“'], [', mai', ', niemals'], ['“abbiamo uscito”', '„abbiamo uscito“'], ['“abbiamo andato”', '„abbiamo andato“'],
  ['. Se una revisione non supera il controllo di fedeltà, il testo originale resta intatto e compare un avviso.', '. Besteht eine Überarbeitung die Treueprüfung nicht, bleibt der Originaltext unverändert und es erscheint ein Hinweis.'],
  ['Infine apri', 'Öffnen Sie abschließend'], ['“Sfoglia l’anteprima”', '„Vorschau durchblättern“'], ['. Il comando di stampa del browser permette di salvare l’opera in PDF A5; usa scala 100% e disattiva intestazioni e piè di pagina.', '. Über den Druckdialog des Browsers können Sie das Werk als A5-PDF speichern. Verwenden Sie 100 % Skalierung und deaktivieren Sie Kopf- und Fußzeilen.'],
  ['Regole chiare', 'Klare Regeln'], ['Prova gratuita e sblocco', 'Kostenlose Testphase und Freischaltung'],
  ['La prova vale per il primo progetto creato dall’account.', 'Die Testphase gilt für das erste im Konto angelegte Projekt.'], ['Dura 14 giorni dalla creazione del progetto.', 'Sie läuft 14 Tage ab Erstellung des Projekts.'],
  ['Permette di lavorare sul primo capitolo e comprende fino a 3 generazioni di capitolo complessive.', 'Sie ermöglicht die Arbeit am ersten Kapitel und umfasst insgesamt bis zu drei Kapitelgenerierungen.'],
  ['I capitoli successivi e il progetto scaduto si aprono dopo lo sblocco amministrativo “Pagato” o “Gratuito”.', 'Weitere Kapitel und ein abgelaufenes Projekt werden nach administrativer Freischaltung als „Bezahlt“ oder „Kostenlos“ zugänglich.'],
  ['Per ora il pagamento avviene tramite bonifico. Scegli la formula nello Studio: lì compariranno le coordinate e la causale. Dopo la verifica manuale, Splendoria sblocca l’intero libro.', 'Derzeit erfolgt die Zahlung per Banküberweisung. Wählen Sie die Edition im Studio; dort werden Bankverbindung und Verwendungszweck angezeigt. Nach manueller Prüfung schaltet Splendoria das gesamte Buch frei.'],
  ['Aiuto immediato', 'Soforthilfe'], ['Se qualcosa non funziona', 'Wenn etwas nicht funktioniert'], ['La Musa non scrive il capitolo', 'Die Muse schreibt das Kapitel nicht'],
  ['Nel capitolo scrivi almeno 50 parole di spunto complessive nelle tre sezioni; le 260–460 parole restano invece una raccomandazione per il materiale generale del libro. Controlla inoltre di essere ancora nei 14 giorni, di non aver esaurito le tre generazioni e di trovarti nel primo capitolo oppure in un libro sbloccato.', 'Schreiben Sie im Kapitel insgesamt mindestens 50 Wörter als Ausgangspunkt über die drei Abschnitte hinweg. Die 260–460 Wörter bleiben eine Empfehlung für das allgemeine Buchmaterial. Prüfen Sie außerdem, ob Sie sich noch innerhalb der 14 Tage befinden, die drei Generierungen nicht aufgebraucht sind und Sie im ersten Kapitel oder in einem freigeschalteten Buch arbeiten.'],
  ['La dettatura non parte', 'Die Diktierfunktion startet nicht'], ['Consenti il microfono nelle impostazioni del browser. La dettatura dipende dal supporto del dispositivo: il campo di testo resta sempre disponibile come alternativa.', 'Erlauben Sie den Mikrofonzugriff in den Browsereinstellungen. Die Diktierfunktion hängt von der Unterstützung des Geräts ab; das Textfeld steht immer als Alternative zur Verfügung.'],
  ['Il salvataggio automatico segnala un errore', 'Die automatische Speicherung meldet einen Fehler'], ['Verifica la connessione e premi “Salva le mie modifiche”. Non chiudere la pagina finché non compare la conferma.', 'Prüfen Sie die Verbindung und wählen Sie „Meine Änderungen speichern“. Schließen Sie die Seite erst, wenn die Bestätigung erscheint.'],
  ['Il testo contiene un fatto inesatto', 'Der Text enthält eine falsche Tatsache'], ['Correggilo direttamente, poi salva. Se vuoi intervenire solo sulla lingua, usa “Correggi grammatica” e rileggi il risultato.', 'Korrigieren Sie die Stelle direkt und speichern Sie. Wenn Sie nur die Sprache überarbeiten möchten, verwenden Sie „Grammatik korrigieren“ und lesen Sie das Ergebnis anschließend durch.'],
  ['Non ricevo un’email', 'Ich erhalte keine E-Mail'], ['Controlla spam e posta indesiderata. Dopo cinque minuti riprova dalla funzione disponibile oppure scrivi a', 'Prüfen Sie Spam und Junk-Mail. Versuchen Sie es nach fünf Minuten erneut oder schreiben Sie an'],
  ['Non trovi la risposta? Scrivi a', 'Keine passende Antwort gefunden? Schreiben Sie an'], [', indicando l’email dell’account e il titolo del progetto, senza inviare la password.', ', und nennen Sie die E-Mail-Adresse des Kontos sowie den Projekttitel. Senden Sie niemals Ihr Passwort.'],
  ['La tua vita in un romanzo', 'Ihr Leben als Roman'], ['Guida allo Studio', 'Leitfaden zum Studio'], ['Termini e condizioni', 'Allgemeine Geschäftsbedingungen'], ['Note legali', 'Rechtliche Hinweise'], ['Trasparenza IA', 'KI-Transparenz'],
  ['Privacy, senza sorprese', 'Datenschutz, ohne Überraschungen'], ['Usiamo solo strumenti tecnici necessari. Niente pubblicità, niente profilazione. Le bozze possono restare sul tuo dispositivo fino a 12 mesi come copia di sicurezza.', 'Wir verwenden nur technisch notwendige Werkzeuge. Keine Werbung, kein Profiling. Entwürfe können als Sicherungskopie bis zu 12 Monate auf Ihrem Gerät verbleiben.'], ['Cookie e dati locali', 'Cookies und lokale Daten'], ['Ho capito', 'Verstanden']
];

const COMMON_EN = [
  ['Guida allo Studio — Splendoria', 'Studio Guide — Splendoria'],
  ['Come funziona', 'How it works'], ['Listino', 'Pricing'], ['Guida', 'Guide'], ['Contattaci', 'Contact us'], ['Il mio Studio', 'My Studio'],
  ['Manuale pratico', 'Practical guide'], ['Il tuo libro, un passo alla volta', 'Your book, one step at a time'],
  ['Questa guida ti accompagna senza conoscenze tecniche: raccogli i fatti, lascia che la Musa ti intervisti, crea l’indice, scrivi e rileggi il primo capitolo.', 'This guide takes you through the process without requiring technical knowledge: gather the facts, let the Muse interview you, create the outline, write and review your first chapter.'],
  ['Crea lo Studio gratuito', 'Create your free Studio'], ['Stampa o salva la guida in PDF', 'Print or save the guide as PDF'], ['Vai direttamente', 'Go directly to'],
  ['Cominciare', 'Getting started'], ['Preparare i ricordi', 'Prepare your memories'], ['Usare la Musa', 'Use the Muse'], ['Rivedere il testo', 'Review the text'], ['Capire la prova', 'Understand the trial'], ['Risolvere i problemi', 'Troubleshooting'],
  ['Passo 1', 'Step 1'], ['Crea il progetto', 'Create the project'], ['Registrati con nome, email e una password di almeno dieci caratteri.', 'Register with your name, email address and a password of at least ten characters.'],
  ['Nello Studio inserisci un titolo provvisorio, scegli il genere e la struttura da 12 o 18 capitoli.', 'In the Studio, enter a working title and choose the genre and a 12- or 18-chapter structure.'], ['Apri il progetto. Titolo, tono e pubblico potranno essere cambiati in seguito.', 'Open the project. You can change the title, tone and audience later.'],
  ['Non serve avere già scritto un testo.', 'You do not need to have written anything already.'], ['Puoi iniziare da ricordi sparsi, oppure usare la dettatura se preferisci raccontare a voce.', 'You can begin with scattered memories, or use dictation if you prefer to tell your story aloud.'],
  ['Passo 2', 'Step 2'], ['Affida fatti sufficienti', 'Provide enough concrete facts'], ['La Musa non deve inventare la tua vita. Prima di chiederle un capitolo, inserisci almeno circa 260–460 parole di materiale concreto e vario, in base alla lunghezza prevista.', 'The Muse must not invent your life. Before asking for a chapter, provide roughly 260–460 words of concrete, varied source material, depending on the intended length.'],
  ['Persone:', 'People:'], ['nomi, ruoli, relazioni e caratteristiche realmente ricordate.', 'names, roles, relationships and characteristics you genuinely remember.'], ['Tempo e luoghi:', 'Time and places:'], ['anni, periodi, città, case, ambienti.', 'years, periods, cities, homes and settings.'],
  ['Azioni e conseguenze:', 'Actions and consequences:'], ['che cosa accadde, chi fece cosa e che cosa cambiò.', 'what happened, who did what and what changed as a result.'], ['Parole ricordate:', 'Remembered words:'], ['usa le virgolette solo per dialoghi realmente forniti.', 'use quotation marks only for dialogue that was actually provided.'],
  ['Senso:', 'Meaning:'], ['che cosa hai compreso e che cosa vuoi lasciare al lettore.', 'what you understood and what you want to leave with the reader.'], ['Se le informazioni non bastano, Splendoria non sostituisce il capitolo con un testo generico: ti chiede di aggiungere altri dati o di completare l’intervista.', 'If the information is insufficient, Splendoria does not replace the chapter with generic text: it asks you to add more facts or complete the interview.'],
  ['Passi 3–5', 'Steps 3–5'], ['Dall’intervista al capitolo', 'From interview to chapter'], ['Salva i ricordi.', 'Save your memories.'], ['Dopo aver confermato la liceità dei contenuti, il salvataggio automatico custodisce le modifiche mentre scrivi.', 'After confirming that you are entitled to use the content, autosave protects your changes while you write.'],
  ['Genera l’intervista.', 'Generate the interview.'], ['Rispondi alle domande una alla volta. Puoi scrivere, dettare oppure chiedere una base alla Musa quando le fonti sono sufficienti.', 'Answer the questions one at a time. You can type, dictate or ask the Muse for a starting draft when the source material is sufficient.'], ['Disegna la trama.', 'Shape the story.'], ['“Disegna la trama del mio libro” crea l’indice completo. Rileggi i titoli prima di proseguire.', '“Shape the story of my book” creates the full outline. Review the chapter titles before continuing.'],
  ['Apri il primo capitolo.', 'Open the first chapter.'], ['Scrivi direttamente oppure premi “Affidati alla Musa”. Attendi la scrittura e la rilettura finale senza chiudere la pagina.', 'Write directly or choose “Entrust it to the Muse”. Wait for writing and final review to finish without closing the page.'], ['Detta', 'Dictate'], ['Trasforma la voce in testo; se il browser non lo consente, scrivi nel campo.', 'Turns your voice into text; if your browser does not support it, type into the field.'],
  ['Migliora', 'Improve'], ['Rende più fluido il testo già presente, senza aggiungere fatti.', 'Makes existing text more fluent without adding facts.'], ['Affidati alla Musa', 'Entrust it to the Muse'], ['Crea una nuova bozza soltanto dalle fonti autorizzate.', 'Creates a new draft only from authorised source material.'], ['Salva', 'Save'], ['Conferma subito le modifiche; l’autosalvataggio resta una protezione aggiuntiva.', 'Saves your changes immediately; autosave remains an additional safeguard.'],
  ['Passo 6', 'Step 6'], ['Rileggi come autore', 'Review it as the author'], ['Controlla sempre nomi, date, luoghi, citazioni, relazioni e ordine degli eventi. Poi usa', 'Always check names, dates, places, quotations, relationships and the order of events. Then use'], ['“Correggi grammatica”', '“Correct grammar”'], [': il revisore interviene su ortografia, sintassi, concordanze, reggenze e punteggiatura, conservando fatti e voce.', ': the reviewer corrects spelling, syntax, grammar and punctuation while preserving the facts and your voice.'],
  ['Splendoria applica un controllo specifico sugli ausiliari italiani: scrive, per esempio,', 'For Italian text, Splendoria applies a specific check to auxiliary verbs and writes, for example,'], ['“siamo usciti”', '“siamo usciti”'], ['“siamo andati”', '“siamo andati”'], [', mai', ', never'], ['“abbiamo uscito”', '“abbiamo uscito”'], ['“abbiamo andato”', '“abbiamo andato”'], ['. Se una revisione non supera il controllo di fedeltà, il testo originale resta intatto e compare un avviso.', '. If a revision does not pass the fidelity check, the original text remains unchanged and a warning appears.'],
  ['Infine apri', 'Finally, open'], ['“Sfoglia l’anteprima”', '“Browse preview”'], ['. Il comando di stampa del browser permette di salvare l’opera in PDF A5; usa scala 100% e disattiva intestazioni e piè di pagina.', '. Your browser’s print command lets you save the work as an A5 PDF; use 100% scale and turn off headers and footers.'],
  ['Regole chiare', 'Clear rules'], ['Prova gratuita e sblocco', 'Free trial and unlocking'], ['La prova vale per il primo progetto creato dall’account.', 'The trial applies to the first project created in the account.'], ['Dura 14 giorni dalla creazione del progetto.', 'It lasts 14 days from the date the project is created.'], ['Permette di lavorare sul primo capitolo e comprende fino a 3 generazioni di capitolo complessive.', 'It lets you work on the first chapter and includes up to three chapter generations in total.'],
  ['I capitoli successivi e il progetto scaduto si aprono dopo lo sblocco amministrativo “Pagato” o “Gratuito”.', 'Later chapters and an expired project become available after administrative unlocking as “Paid” or “Free”.'], ['Per ora il pagamento avviene tramite bonifico. Scegli la formula nello Studio: lì compariranno le coordinate e la causale. Dopo la verifica manuale, Splendoria sblocca l’intero libro.', 'For now, payment is made by bank transfer. Choose your edition in the Studio; the bank details and payment reference will appear there. After manual verification, Splendoria unlocks the full book.'],
  ['Aiuto immediato', 'Immediate help'], ['Se qualcosa non funziona', 'If something is not working'], ['La Musa non scrive il capitolo', 'The Muse does not write the chapter'], ['Nel capitolo scrivi almeno 50 parole di spunto complessive nelle tre sezioni; le 260–460 parole restano invece una raccomandazione per il materiale generale del libro. Controlla inoltre di essere ancora nei 14 giorni, di non aver esaurito le tre generazioni e di trovarti nel primo capitolo oppure in un libro sbloccato.', 'Write at least 50 words of source material across the three chapter sections. The 260–460 words remain a recommendation for the book’s general source material. Also check that you are still within the 14-day period, have not used all three generations, and are working in the first chapter or an unlocked book.'],
  ['La dettatura non parte', 'Dictation does not start'], ['Consenti il microfono nelle impostazioni del browser. La dettatura dipende dal supporto del dispositivo: il campo di testo resta sempre disponibile come alternativa.', 'Allow microphone access in your browser settings. Dictation depends on device support; the text field is always available as an alternative.'], ['Il salvataggio automatico segnala un errore', 'Autosave reports an error'], ['Verifica la connessione e premi “Salva le mie modifiche”. Non chiudere la pagina finché non compare la conferma.', 'Check your connection and press “Save my changes”. Do not close the page until the confirmation appears.'],
  ['Il testo contiene un fatto inesatto', 'The text contains an inaccurate fact'], ['Correggilo direttamente, poi salva. Se vuoi intervenire solo sulla lingua, usa “Correggi grammatica” e rileggi il risultato.', 'Correct it directly, then save. If you only want to improve the language, use “Correct grammar” and review the result.'], ['Non ricevo un’email', 'I am not receiving an email'], ['Controlla spam e posta indesiderata. Dopo cinque minuti riprova dalla funzione disponibile oppure scrivi a', 'Check spam and junk mail. After five minutes, try the available function again or write to'], ['Non trovi la risposta? Scrivi a', 'Still cannot find the answer? Write to'], [', indicando l’email dell’account e il titolo del progetto, senza inviare la password.', ', stating the account email address and project title, without sending your password.'],
  ['La tua vita in un romanzo', 'Your life as a novel'], ['Guida allo Studio', 'Studio Guide'], ['Termini e condizioni', 'Terms and conditions'], ['Note legali', 'Legal notice'], ['Trasparenza IA', 'AI transparency'], ['Privacy, senza sorprese', 'Privacy, without surprises'], ['Usiamo solo strumenti tecnici necessari. Niente pubblicità, niente profilazione. Le bozze possono restare sul tuo dispositivo fino a 12 mesi come copia di sicurezza.', 'We use only technically necessary tools. No advertising, no profiling. Drafts may remain on your device for up to 12 months as a backup copy.'], ['Cookie e dati locali', 'Cookies and local data'], ['Ho capito', 'Got it']
];

const ATTRS = {
  de: [['Navigazione principale', 'Hauptnavigation'], ['Indice della guida', 'Inhaltsverzeichnis des Leitfadens'], ['Informazioni e assistenza', 'Informationen und Hilfe'], ['Chiudi l’informativa privacy', 'Datenschutzhinweis schließen'], ['Informazioni privacy', 'Datenschutzinformationen']],
  en: [['Navigazione principale', 'Main navigation'], ['Indice della guida', 'Guide contents'], ['Informazioni e assistenza', 'Information and support'], ['Chiudi l’informativa privacy', 'Close privacy notice'], ['Informazioni privacy', 'Privacy information']]
};

export function localizeGuideHtml(html, locale) {
  const entries = locale === 'de' ? COMMON_DE : COMMON_EN;
  html = applyTextMap(html, entries);
  html = applyAttributeMap(html, ATTRS[locale]);
  html = localizePublicSeo(html, locale, META[locale], GUIDE_PATHS);
  html = rewriteExactHrefs(html, {
    '/': `/${locale}/`,
    '/#metodo': `/${locale}/#metodo`,
    '/#formule': `/${locale}/#formule`,
    '/#contatti': `/${locale}/#contatti`,
    '/guida': GUIDE_PATHS[locale]
  });
  return html;
}
